version: "3"
services:
    aio-restrabbit:
      build: .
      image: studitemps/aio-restrabbit
      container_name: aio-restrabbit
      volumes:
        - ./conf:/usr/src/app/conf
      network_mode: bridge
